#pragma once

/* ========================================
 * PLOOPY ADEPT CONFIG - v1.0.1
 * ======================================== */

#define PLOOPY_TRACKBALL_CPI 1600
#define PLOOPY_DRAGSCROLL_DPI 100
#define PLOOPY_DRAGSCROLL_INVERT_Y
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE

#define ACCEL_OFFSET 10
#define ACCEL_SLOPE 1.5
#define ACCEL_LIMIT 4.0

#define SCROLL_SENSITIVITY 0.9f

#define NAV_THRESHOLD 450
#define NAV_COOLDOWN 300

#define MEDIA_THRESHOLD 150

#define TAPPING_TERM 200
#define POINTING_DEVICE_TASK_THROTTLE_MS 1

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#define COMBO_TERM 250
#define COMBO_MUST_HOLD_MODS
#define COMBO_HOLD_TERM 2000

#define ACCUMULATOR_OVERFLOW_LIMIT 10000
#define TIMER_ROLLOVER_RESET 60000

#define DEFAULT_DPI_INDEX 1

/* --- LOCK STATE COORDINATION --- */
#define LOCKSTATE_ENABLE

#ifdef LOCKSTATE_ENABLE
#define LOCK_POLL_INTERVAL 50
#endif

