#pragma once

#define PLOOPY_TRACKBALL_CPI 1600
#define PLOOPY_DRAGSCROLL_DPI 100
#define PLOOPY_DRAGSCROLL_INVERT_Y
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE

#define TAPPING_TERM 200
#define POINTING_DEVICE_TASK_THROTTLE_MS 1

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#define COMBO_TERM 250
#define COMBO_MUST_HOLD_MODS
#define COMBO_HOLD_TERM 2000
